// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIt1yx0y-TeyxUYtqZwKpLVw-JmMNiOOQ',
    appId: '1:303483063451:web:0b0331b69c1743c591ca3e',
    messagingSenderId: '303483063451',
    projectId: 'erasofttask',
    authDomain: 'erasofttask.firebaseapp.com',
    storageBucket: 'erasofttask.firebasestorage.app',
    measurementId: 'G-9BFVBC58GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKRyUNpzuWR9DToTtQD_VH1BY4iOPrjE',
    appId: '1:303483063451:android:43ed0008a7cea08991ca3e',
    messagingSenderId: '303483063451',
    projectId: 'erasofttask',
    storageBucket: 'erasofttask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5tdSKKZTiDE-mbVxvIgdBnY2CMQa687E',
    appId: '1:303483063451:ios:78b78e3e37d9264991ca3e',
    messagingSenderId: '303483063451',
    projectId: 'erasofttask',
    storageBucket: 'erasofttask.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5tdSKKZTiDE-mbVxvIgdBnY2CMQa687E',
    appId: '1:303483063451:ios:78b78e3e37d9264991ca3e',
    messagingSenderId: '303483063451',
    projectId: 'erasofttask',
    storageBucket: 'erasofttask.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIt1yx0y-TeyxUYtqZwKpLVw-JmMNiOOQ',
    appId: '1:303483063451:web:0b3c8ab8604f0f2891ca3e',
    messagingSenderId: '303483063451',
    projectId: 'erasofttask',
    authDomain: 'erasofttask.firebaseapp.com',
    storageBucket: 'erasofttask.firebasestorage.app',
    measurementId: 'G-X80D5G4N1H',
  );
}
